import { readFileSync } from "node:fs";

import { expect, test } from "bun:test";

import { site } from "@/lib/site";
import { WORDMARK, WORDMARK_DOTS } from "@/lib/wordmark-dots";

test("the baked mark still spells the handle", () => {
  // The dots are coordinates, not glyphs — nothing at runtime can re-letter
  // them. If the handle changes, the art has to be regenerated by hand:
  //   bun tools/gen-dots.mjs --preset '{"text":"…"}' > lib/wordmark-dots.ts
  expect(WORDMARK.text).toBe(site.handle.toLowerCase());
});

test("the coordinates are whole pairs inside the box", () => {
  expect(WORDMARK_DOTS.length).toBeGreaterThan(1000);
  expect(WORDMARK_DOTS.length % 2).toBe(0);

  for (let i = 0; i < WORDMARK_DOTS.length; i += 2) {
    const x = WORDMARK_DOTS[i];
    const y = WORDMARK_DOTS[i + 1];
    expect(Number.isInteger(x)).toBe(true);
    expect(Number.isInteger(y)).toBe(true);
    expect(x).toBeGreaterThanOrEqual(0);
    expect(y).toBeGreaterThanOrEqual(0);
    expect(x).toBeLessThanOrEqual(WORDMARK.box.width);
    expect(y).toBeLessThanOrEqual(WORDMARK.box.height);
  }
});

test("the lettering is centred and fills its box", () => {
  let minX = Infinity;
  let maxX = -Infinity;
  let minY = Infinity;
  let maxY = -Infinity;

  for (let i = 0; i < WORDMARK_DOTS.length; i += 2) {
    minX = Math.min(minX, WORDMARK_DOTS[i]);
    maxX = Math.max(maxX, WORDMARK_DOTS[i]);
    minY = Math.min(minY, WORDMARK_DOTS[i + 1]);
    maxY = Math.max(maxY, WORDMARK_DOTS[i + 1]);
  }

  // A run of dots that had lost a glyph, or drifted off the optical centre,
  // would show up here before it showed up in a screenshot.
  expect(maxX - minX).toBeGreaterThan(WORDMARK.box.width * 0.9);
  expect(maxY - minY).toBeGreaterThan(WORDMARK.box.height * 0.7);
  expect(Math.abs(minX - (WORDMARK.box.width - maxX))).toBeLessThan(24);
});

test("the crop takes lettering, not empty box", () => {
  const edge = WORDMARK.box.height * WORDMARK.visible;
  let below = 0;
  for (let i = 1; i < WORDMARK_DOTS.length; i += 2) {
    if (WORDMARK_DOTS[i] > edge) below += 1;
  }

  // The point of the crop is that the letters run off the page. A mark drawn
  // with room to spare under the baseline would clear this line and the
  // signature would just sit above the edge like everything else.
  expect(WORDMARK.visible).toBeGreaterThan(0.5);
  expect(WORDMARK.visible).toBeLessThan(1);
  expect(below).toBeGreaterThan(WORDMARK_DOTS.length / 2 / 100);
});

test("the cursor field is a real circle with a real push", () => {
  expect(WORDMARK.repelRadius).toBeGreaterThan(0);
  expect(WORDMARK.repelStrength).toBeGreaterThan(0);
  // A push that outruns its own circle would fling dots past the edge of the
  // field and let them re-enter it, which reads as a flicker.
  expect(WORDMARK.repelStrength).toBeLessThan(WORDMARK.repelRadius);
});

test("--signature-clear still clears the signature", () => {
  // The dock and the way back up sit at `--signature-clear` above the last
  // pixel of the page, and the mark runs the full width of the viewport — so
  // the number in globals.css is a fraction of `vw` derived from the box here.
  // Regenerating the art at a new box would silently drop a control onto it.
  const css = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");
  const vw = css.match(/--signature-clear:\s*calc\(([\d.]+)vw/)?.[1];
  expect(vw).toBeDefined();

  const kept = (WORDMARK.box.height * WORDMARK.visible) / WORDMARK.box.width;
  expect(Number(vw) / 100).toBeCloseTo(kept, 4);
});

test("the mark has side bearing, so it reads as running off rather than trimmed", () => {
  let left = Infinity;
  let right = -Infinity;
  for (let i = 0; i < WORDMARK_DOTS.length; i += 2) {
    if (WORDMARK_DOTS[i] < left) left = WORDMARK_DOTS[i];
    if (WORDMARK_DOTS[i] > right) right = WORDMARK_DOTS[i];
  }
  expect(left).toBeGreaterThan(WORDMARK.box.width * 0.005);
  expect(right).toBeLessThan(WORDMARK.box.width * 0.995);
});
